name: electro
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.4.1
  google_fonts: ^6.2.1
  pretty_dio_logger: ^1.4.0
  lottie: ^3.1.3
  logger: ^2.4.0
  hive_flutter: ^1.1.0
  get_it: ^8.0.2
  gap: ^3.0.1
  flutter_svg: ^2.0.13
  flutter_screenutil: ^5.9.3
  dio: ^5.7.0
  flutter_bloc: ^8.1.6
  file_picker: ^8.1.3
  cached_network_image: ^3.2.3
  shared_preferences: ^2.3.2
  device_preview: ^1.2.0
  restart_app: ^1.3.2
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_analytics: ^11.3.3
  # flutter_local_notifications: ^17.2.1+2
  json_annotation: ^4.9.0
  flutter_localization: ^0.2.2
  dartz: ^0.10.1
  flutter_spinkit: ^5.2.1
  timeline_tile: ^2.0.0
  percent_indicator: ^4.2.4
  image_picker: ^1.1.2
  pdf: ^3.11.1
  printing: ^5.13.4
  flutter_image_compress: ^2.4.0
  http: ^1.3.0
  path_provider: ^2.1.5
  carousel_slider_plus: ^7.1.0
  icons_plus: ^5.0.0
  flutter_native_splash: ^2.4.6
  equatable: ^2.0.7
  fluttertoast: ^8.2.12
  number_pagination: ^1.1.6
  firebase_auth: ^5.5.3
  google_sign_in: ^6.3.0





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/animations/
    - assets/lang/ar.json
    - assets/lang/en.json

  fonts:
    - family: IBMPlexMono
      fonts:
        - asset: assets/fonts/IBMPlexMono-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexMono-Bold.ttf
          weight: 700

